### PR TITLE
Autofill feature for the seach bar that supports default labels (not customizable)

### LINKED ISSUE #37: [FEATURE] UI for searching for labels from the calendar view
**Is your feature request related to a problem? Please describe.**

Currently there is no way to search for the labels that we have added to the different documents.

**Describe the solution you'd like**

I would like to add the ability to search for labels from the calendar view which would return the list of documents with that label attached to them.

**Additional context**

### LINKED ISSUE #47: [FEATURE] Autofill suggested lables in the searchbar (does not support custom labels) - for notes
**Is your feature request related to a problem? Please describe.**
NB: it is not a technical problem, but rather a solution for when the user forgets the label names they have created.
Our notes page allows custom-made labels, which means that with time the users might forget the exam names of the labels, which is required for searching. So instead we can offer autofill - they can see all the labels with similar letters. 

**Describe the solution you'd like**
While they type in letters in the searchbar, all of the labels with similar letter combinations show up. 

**Additional context**

### PR DESCRIPTION
**Pull request by madhoolikacvss**
# Pull Request Template

## Description
In order to make it easier for the users to search for labeled notes, we need an autofill feature that shows all the available labels with the same letter combination as the user's input. This PR also fixes the following issues cause by this addition:
Fixes # (issue)
- ensures the header div does not expand with the dropdown
- the dropdown disappears when the user clicks elsewhere on the screen 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
Tested using a default array of labels. However, did not run it through Codacy or Prettier. 

## Related GitHub Issue
Please link to the related GitHub issue (if applicable).
https://github.com/cse110-sp24-group2/cse110-sp24-group2/issues/37
https://github.com/cse110-sp24-group2/cse110-sp24-group2/issues/47

Closes #37 
Closes #47

## Testing
- [ ] add testing to your new functionality, either in the form of unit tests or e2e tests.ease also list any relevant details for your test configuration

## Code Documentation
- [ ] Document code using JSDoc comments so that it can be properly documented and help others.
- [ ] Ensure that functions are not stuck within other functions otherwise JSDoc may struggle with pulling the documentation.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by BrianMorse12604** [comment]
Please move the search-bar.js file to the component folder

**Comment by udsingla** [comment]
I have changed the location of search-bar.js to components and fixed the codacy issue line that was highlighted.

**Comment by madhoolikacvss** [comment]
I added monthValues.js to the folder to address the DRY issue - monthColour and monthClasses are used by both search-bar.js and calendar-script.js so I made monthValues.js with all information regarding months that both files can access. It decreases repetition.

**Comment by WishingWell13** [comment]
Not making it a component, will merge into an HTML file.

**Pull request closed without merging**
