### PR TITLE
Adding hand testing videos

### LINKED ISSUE #195: [DOCS] Upload Hand Testing Videos From Slack
**Is your feature request related to a problem? Please describe.**

We have a few hand testing / demo videos and screenshots. We should upload those to `admin` folder

image

**Describe the solution you'd like**

There should be a few videos from me in the slack. Download them and upload them to the repo. Create a new folder under admin named "hand-testing"

**Additional context**

### PR DESCRIPTION
**Pull request by udsingla**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Added videos of hand testing features and also demonstration of current iterations of app over the timeline of the project.

Fixes #195  (issue)

## Related GitHub Issue
Please link to the related GitHub issue (if applicable).
[Link to issue](https://github.com/cse110-sp24-group2/cse110-sp24-group2/issues/195)

### CODE REVIEW

**Comment by udsingla** [comment]
Please take a look at the videos and if you feel any of those should be removed or any other videos should be added, let me know.

**Comment by BrianMorse12604** [comment]
Could you rename the videos so that what they are testing is more clear from the start?

**Comment by udsingla** [comment]
Changed the name of the videos to describe what they are about.

**Review by BrianMorse12604 — APPROVED** [review]
Thanks for the visual demonstration and tests

**Pull request merged**
